variable "aws_region" {
  description = "AWS region"
  type        = string
}

variable "environment" {
  description = "Environment name"
  type        = string
}

variable "cluster_name" {
  description = "Name of the ECS cluster"
  type        = string
}

variable "vpc_tags" {
  description = "Tags to find the VPC"
  type        = map(string)
  default = {
    Environment = "development"
  }
}

variable "public_subnet_tags" {
  description = "Tags to find the public subnets"
  type        = map(string)
  default = {
    Environment = "development"
    Type        = "Public"
  }
}

variable "tags" {
  description = "Default tags for all resources"
  type        = map(string)
  default = {
    Terraform    = "true"
    Environment  = "development"
    Project      = "dd-demo"
    Project_code = "abc1234"
  }
}

variable "project_name" {
  description = "Name of the project"
  type        = string
  default     = "dd-demo"
}

# Datadog Configuration
variable "datadog_external_id" {
  description = "External ID generated by Datadog for AWS integration"
  type        = string
}

variable "datadog_api_key" {
  description = "Datadog API key"
  type        = string
  sensitive   = true
}

variable "datadog_app_key" {
  description = "Datadog Application key"
  type        = string
  sensitive   = true
}
